Traceback (most recent call last):
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\luuka\Anaconda3\envs\jb1\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path_saved_images = "/content/drive/MyDrive/Colab Notebooks/flame_front_analysis_images/saved_images/"
fig1.savefig(path_saved_images + "SL0_phi_T_u=" + str(int(T_u)) + "_p_u=" +str(int(p_u))+ ".svg", dpi=300)
fig2.savefig(path_saved_images + "Tad_phi_" + str(int(T_u)) + "_p_u=" +str(int(p_u))+ ".svg", dpi=300)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_17524/3999839868.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mpath_saved_images[0m [1;33m=[0m [1;34m"/content/drive/MyDrive/Colab Notebooks/flame_front_analysis_images/saved_images/"[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mfig1[0m[1;33m.[0m[0msavefig[0m[1;33m([0m[0mpath_saved_images[0m [1;33m+[0m [1;34m"SL0_phi_T_u="[0m [1;33m+[0m [0mstr[0m[1;33m([0m[0mint[0m[1;33m([0m[0mT_u[0m[1;33m)[0m[1;33m)[0m [1;33m+[0m [1;34m"_p_u="[0m [1;33m+[0m[0mstr[0m[1;33m([0m[0mint[0m[1;33m([0m[0mp_u[0m[1;33m)[0m[1;33m)[0m[1;33m+[0m [1;34m".svg"[0m[1;33m,[0m [0mdpi[0m[1;33m=[0m[1;36m300[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mfig2[0m[1;33m.[0m[0msavefig[0m[1;33m([0m[0mpath_saved_images[0m [1;33m+[0m [1;34m"Tad_phi_"[0m [1;33m+[0m [0mstr[0m[1;33m([0m[0mint[0m[1;33m([0m[0mT_u[0m[1;33m)[0m[1;33m)[0m [1;33m+[0m [1;34m"_p_u="[0m [1;33m+[0m[0mstr[0m[1;33m([0m[0mint[0m[1;33m([0m[0mp_u[0m[1;33m)[0m[1;33m)[0m[1;33m+[0m [1;34m".svg"[0m[1;33m,[0m [0mdpi[0m[1;33m=[0m[1;36m300[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\jb1\lib\site-packages\matplotlib\figure.py[0m in [0;36msavefig[1;34m(self, fname, transparent, **kwargs)[0m
[0;32m   3003[0m                 [0mpatch[0m[1;33m.[0m[0mset_edgecolor[0m[1;33m([0m[1;34m'none'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   3004[0m [1;33m[0m[0m
[1;32m-> 3005[1;33m         [0mself[0m[1;33m.[0m[0mcanvas[0m[1;33m.[0m[0mprint_figure[0m[1;33m([0m[0mfname[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   3006[0m [1;33m[0m[0m
[0;32m   3007[0m         [1;32mif[0m [0mtransparent[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\jb1\lib\site-packages\matplotlib\backend_bases.py[0m in [0;36mprint_figure[1;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[0;32m   2253[0m                 [1;31m# force the figure dpi to 72), so we need to set it again here.[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2254[0m                 [1;32mwith[0m [0mcbook[0m[1;33m.[0m[0m_setattr_cm[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mfigure[0m[1;33m,[0m [0mdpi[0m[1;33m=[0m[0mdpi[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2255[1;33m                     result = print_method(
[0m[0;32m   2256[0m                         [0mfilename[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2257[0m                         [0mfacecolor[0m[1;33m=[0m[0mfacecolor[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\jb1\lib\site-packages\matplotlib\backends\backend_svg.py[0m in [0;36mprint_svg[1;34m(self, filename, *args, **kwargs)[0m
[0;32m   1319[0m             [0m__[0m [0mDC_[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1320[0m         """
[1;32m-> 1321[1;33m         [1;32mwith[0m [0mcbook[0m[1;33m.[0m[0mopen_file_cm[0m[1;33m([0m[0mfilename[0m[1;33m,[0m [1;34m"w"[0m[1;33m,[0m [0mencoding[0m[1;33m=[0m[1;34m"utf-8"[0m[1;33m)[0m [1;32mas[0m [0mfh[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1322[0m [1;33m[0m[0m
[0;32m   1323[0m             [0mfilename[0m [1;33m=[0m [0mgetattr[0m[1;33m([0m[0mfh[0m[1;33m,[0m [1;34m'name'[0m[1;33m,[0m [1;34m''[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\jb1\lib\contextlib.py[0m in [0;36m__enter__[1;34m(self)[0m
[0;32m    117[0m         [1;32mdel[0m [0mself[0m[1;33m.[0m[0margs[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mkwds[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mfunc[0m[1;33m[0m[1;33m[0m[0m
[0;32m    118[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 119[1;33m             [1;32mreturn[0m [0mnext[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mgen[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    120[0m         [1;32mexcept[0m [0mStopIteration[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    121[0m             [1;32mraise[0m [0mRuntimeError[0m[1;33m([0m[1;34m"generator didn't yield"[0m[1;33m)[0m [1;32mfrom[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\jb1\lib\site-packages\matplotlib\cbook\__init__.py[0m in [0;36mopen_file_cm[1;34m(path_or_file, mode, encoding)[0m
[0;32m    475[0m [1;32mdef[0m [0mopen_file_cm[0m[1;33m([0m[0mpath_or_file[0m[1;33m,[0m [0mmode[0m[1;33m=[0m[1;34m"r"[0m[1;33m,[0m [0mencoding[0m[1;33m=[0m[1;32mNone[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    476[0m     [1;34mr"""Pass through file objects and context-manage path-likes."""[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 477[1;33m     [0mfh[0m[1;33m,[0m [0mopened[0m [1;33m=[0m [0mto_filehandle[0m[1;33m([0m[0mpath_or_file[0m[1;33m,[0m [0mmode[0m[1;33m,[0m [1;32mTrue[0m[1;33m,[0m [0mencoding[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    478[0m     [1;32mif[0m [0mopened[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    479[0m         [1;32mwith[0m [0mfh[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\jb1\lib\site-packages\matplotlib\cbook\__init__.py[0m in [0;36mto_filehandle[1;34m(fname, flag, return_opened, encoding)[0m
[0;32m    460[0m             [0mfh[0m [1;33m=[0m [0mbz2[0m[1;33m.[0m[0mBZ2File[0m[1;33m([0m[0mfname[0m[1;33m,[0m [0mflag[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    461[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 462[1;33m             [0mfh[0m [1;33m=[0m [0mopen[0m[1;33m([0m[0mfname[0m[1;33m,[0m [0mflag[0m[1;33m,[0m [0mencoding[0m[1;33m=[0m[0mencoding[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    463[0m         [0mopened[0m [1;33m=[0m [1;32mTrue[0m[1;33m[0m[1;33m[0m[0m
[0;32m    464[0m     [1;32melif[0m [0mhasattr[0m[1;33m([0m[0mfname[0m[1;33m,[0m [1;34m'seek'[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/flame_front_analysis_images/saved_images/SL0_phi_T_u=293_p_u=101325.svg'
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/flame_front_analysis_images/saved_images/SL0_phi_T_u=293_p_u=101325.svg'

